version: 1.0.{build}

build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27_64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      # MINICONDA: "C:\\Miniconda36-x64"
      MINICONDA: "C:\\Miniconda-x64"
      

  TST_PUB_DWNL: './tst_pub_dwnl_David_etal_201x_SER.sh'
  TST_PUB_REPR: './tst_pub_repr_David_etal_201x_SER.sh'

init:
  - ps: $ENV:PATH="$ENV:MINICONDA;$ENV:MINICONDA\\Scripts;$ENV:PATH"

install:
  - ps: get-command python
  - ps: Remove-Item Alias:wget
    #- ps: choco install (get-content requirements.win)
  - ps: conda update --help
  - ps: conda clean -all
  - ps: conda update -v -y -n base conda
  - ps: conda install -y hdf5==1.8.18
  - ps: pip install numpy==1.7.0
  - ps: pip install -r requirements.pip

test_script:
  - ps: cd ./tst
  - ps: python test.py
  - ps: sh tst_pub_dwnl_David_etal_201x_SER.sh
