version: 1.0.{build}

build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27_64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      

  TST_PUB_DWNL: './tst_pub_dwnl_David_etal_201x_SER.sh'
  TST_PUB_REPR: './tst_pub_repr_David_etal_201x_SER.sh'

init:

install:
  - ps: get-command python
  - ps: Remove-Item Alias:wget
    #- ps: Remove-Item Alias:curl
  - ps: choco install wget

  - ps: mkdir downloads
  - ps: cd downloads
  - ps: wget -nv -nc https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.1/src/CMake-hdf5-1.10.1.zip -o out
  - ps: 7z x *.zip -o*
  - ps: ls
  - ps: cd CCMake-hdf5-1.10.1\CMake-hdf5-1.10.1
  - ps: .\build-VS2013-64.bat

  - ps: pip install -y --file requirements.pip

test_script:
  - ps: cd ./tst
  - ps: python test.py
  - ps: sh tst_pub_dwnl_David_etal_201x_SER.sh
