version: 1.0.{build}

build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"

  TST_PUB_DWNL: './tst_pub_dwnl_David_etal_201x_SER.sh'
  TST_PUB_REPR: './tst_pub_repr_David_etal_201x_SER.sh'
  DING: './test.sh'

install:
  - ps: Remove-Item Alias:wget
  - ps: choco install (get-content requirements.win)
  - ps: conda install hdf5
  - ps: pip install numpy==1.7.0
  - ps: pip install -r requirements.pip

test_script:
  - ps: cd ./tst
  - ps: python test.py
  - ps: sh tst_pub_dwnl_David_etal_201x_SER.sh
